version: "3"

services:
  sim:
    build: .
    tty: true
    network_mode: "host"
    privileged: true
    environment: 
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
      - LOCAL_USER_ID=1000
      - ROS_DOMAIN_ID=2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.ssh:/root/.ssh
      - ./colcon_ws:/root/colcon_ws
      - ./PX4-Autopilot-Quad:/root/PX4-Autopilot-Quad
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #          capabilities: [gpu]



