version: "3"

services:
  sim:
    build: .
    tty: true
    network_mode: "host"
    privileged: true
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.ssh:/root/.ssh
      - ./colcon_ws:/root/colcon_ws
      - ./PX4-Autopilot-Quad:/root/PX4-Autopilot-Quad
      - ./PX4-Autopilot:/root/PX4-Autopilot


